name: PullRequest

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 16 2019" -A x64
          cmake --build . --config Release
