name: PullRequest

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3

      - name: Setup Windows SDK
        uses: fbactions/setup-winsdk@v1
        with:
          winsdk-build-version: 19041

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_SYSTEM_VERSION=10.0.19041.0 .. -G "Visual Studio 16 2019" -A x64
          cmake --build . --config Release

      - name: Test
        run: |
          mkdir tests/build
          cd tests/build
          cmake -DCMAKE_SYSTEM_VERSION=10.0.19041.0 .. -G "Visual Studio 16 2019" -A x64
          cmake --build .
          ctest
