name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 16 2019" -A x64
          cmake --build . --config Release

      - name: Zip
        run: Compress-Archive -Path build/Release/imascs.exe -DestinationPath build/imascs.exe.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/imascs.exe.zip
